name: a-gadget
version: 16-0.1
summary: gadget for a-sample
description: |
 Bootloader files and partitoning data to create a
 bootable Ubuntu Core image.
base: core20
type: gadget
architectures:
  - armhf
confinement: strict
grade: stable

parts:
  uboot:
    plugin: nil
    source: u-boot/stage
    source-type: local
    override-build: |
      cp u-boot $SNAPCRAFT_PART_INSTALL/
      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/boot.sel ./uboot.env.in
      touch $SNAPCRAFT_PART_INSTALL/uboot.conf

    build-packages:
      - tree