name: a-kernel
version: '0.1'
summary: a-sample-kernel snap
description: |
  tbd

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

type: kernel
build-base: core20
architectures:
  - build-on: amd64
    run-on: armhf

parts:
  kernel:
    plugin: nil
    source: kernel-5.17/stage
    source-type: local
    override-build: |
      cp zImage $SNAPCRAFT_PART_INSTALL/zImage
      cp -rv dtb* $SNAPCRAFT_PART_INSTALL/dtb

    build-packages:
        - tree
